language: php
php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer update

script:
  - vendor/bin/phpunit --coverage-text -c test/

after_script:
  - php vendor/bin/coveralls
